[profile.default]
# Project
# https://book.getfoundry.sh/reference/config/project
src = 'contracts'
test = 'test/foundry'
no_match_test = "testDiff"
out = 'out'
libs = [
  'node_modules',
  'lib'
]
cache = true
cache_path = 'forge-cache'
force = false
remappings = [
  'ds-test/=lib/forge-std/lib/ds-test/src/',
  '@beanstalk/=node_modules/@beanstalk/',
  '@ethereum-waffle/=node_modules/@ethereum-waffle/',
  '@openzeppelin/=node_modules/@openzeppelin/',
  '@uniswap/=node_modules/@uniswap/',
  'base64-sol/=node_modules/@uniswap/v3-periphery/node_modules/base64-sol/',
  'erc4626-tests/=node_modules/@beanstalk/wells/lib/openzeppelin-contracts-upgradeable/lib/erc4626-tests/',
  'eth-gas-reporter/=node_modules/eth-gas-reporter/',
  'forge-std/=node_modules/forge-std/',
  'hardhat/=node_modules/hardhat/',
  'openzeppelin-contracts-upgradeable/=node_modules/@beanstalk/wells/lib/openzeppelin-contracts-upgradeable/',
  'openzeppelin-contracts/=node_modules/@beanstalk/wells/lib/openzeppelin-contracts/',
  'prb-math/=node_modules/@beanstalk/wells/lib/prb-math/',
  'prb-test/=node_modules/@beanstalk/wells/lib/prb-math/lib/prb-test/',
  'uniswap/=node_modules/uniswap/',
]

# Compiler
# https://book.getfoundry.sh/reference/config/solidity-compiler
libraries = []
auto_detect_solc = true
ignored_error_codes = [1878, 2837]
optimizer = true
optimizer_runs = 200
via_ir = false
bytecode_hash = 'ipfs'

# Testing
# https://book.getfoundry.sh/reference/config/testing
verbosity = 0
ffi = true
fs_permissions = [{ access = "read", path = "./out" }]
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72' # The value of `msg.sender` in tests.
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72' # The value of `tx.origin` in tests.
gas_reports = ['*']
 # Cache to `$HOME/.foundry/cache/<chain id>/<block number>`.
no_storage_caching = false
 
[profile.differential]
match_test = "testDiff"
no_match_test = "a^"

# Formatter
# https://book.getfoundry.sh/reference/config/formatter
# ...pass...
[profile.default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'


